// Generated by open-dynamic-workflows. Keep this tiny wrapper in your project.
export { default } from "file:///C:/Users/oghyh/Coding/Githubs/open-dynamic-workflows/packages/opencode-plugin/src/index.js";
export * from "file:///C:/Users/oghyh/Coding/Githubs/open-dynamic-workflows/packages/opencode-plugin/src/index.js";
